/**
 * Single source of truth for case + template data inside the React tree.
 *
 * On SSG (build time) we statically import the JSON so every detail/category
 * page has the data available without a fetch — that's what makes the static
 * HTML output meaningful for SEO. The same import works at runtime in the
 * browser; Vite inlines the JSON into a hashed chunk that's downloaded once
 * and cached, shared across all routes.
 *
 * The dataset is kept lean on purpose: `seoTitle`/`seoDescription` are derived
 * at render time (see src/lib/seo-url.mjs) rather than stored, and unused
 * computed fields (`difficulty`, `commercialOk`) aren't persisted. See
 * scripts/migrate-v2.mjs for the field policy.
 *
 * RUNTIME VALIDATION
 *   The JSON is generated by build scripts, so a malformed record means a
 *   build bug, not user input. Rather than ship a schema validator (zod et al.)
 *   into the client bundle, we run a cheap structural check that is a NO-OP in
 *   the production browser build and throws loudly during dev / SSG. That way a
 *   missing `slug` or an unknown `userCategory` fails the build instead of
 *   silently rendering a broken page — closing the "types are decorative"
 *   gap at the JSON→runtime boundary without runtime cost in prod.
 */
import casesJson from "../../public/data/cases.json";
import templatesJson from "../../public/data/templates.json";
import type { PromptCase, PromptTemplate, UserCategoryKey } from "../types";

const USER_CATEGORY_KEYS: ReadonlySet<string> = new Set<UserCategoryKey>([
  "xhs-cover",
  "wechat-grid",
  "merchant-poster",
  "portrait",
  "kids-portrait",
  "3d-ip",
  "ecommerce",
  "travel-poster",
  "brand-kv",
  "festival",
  "infographic",
  "sticker",
  "ui-screenshot",
  "poster-general",
  "illustration",
  "classical",
  "storyboard",
  "architecture",
  "other",
]);

/**
 * Structural validation of the generated dataset. Throws on the first
 * malformed record. Only invoked outside the production browser build (see
 * below), so it costs nothing at runtime for end users.
 */
function validateCases(raw: unknown): PromptCase[] {
  if (!Array.isArray(raw)) {
    throw new Error(`[data] cases.json must be an array, got ${typeof raw}`);
  }
  const slugs = new Set<string>();
  raw.forEach((c, i) => {
    const where = `cases.json[${i}] (id=${(c as { id?: unknown })?.id ?? "?"})`;
    if (!c || typeof c !== "object") throw new Error(`[data] ${where} is not an object`);
    const rec = c as Record<string, unknown>;
    for (const field of ["id", "slug", "title", "imageUrl", "ratio", "userCategory", "createdAt"]) {
      if (typeof rec[field] !== "string" || (rec[field] as string).length === 0) {
        throw new Error(`[data] ${where} missing required string field "${field}"`);
      }
    }
    if (!USER_CATEGORY_KEYS.has(rec.userCategory as string)) {
      throw new Error(
        `[data] ${where} has unknown userCategory "${rec.userCategory}". ` +
          `Add it to UserCategoryKey + USER_CATEGORIES, or fix the classifier.`,
      );
    }
    if (rec.userCategories !== undefined) {
      if (!Array.isArray(rec.userCategories)) {
        throw new Error(`[data] ${where} userCategories must be an array`);
      }
      for (const k of rec.userCategories as unknown[]) {
        if (!USER_CATEGORY_KEYS.has(k as string)) {
          throw new Error(`[data] ${where} has unknown secondary userCategory "${k}"`);
        }
      }
    }
    for (const arrField of ["tags", "styles", "scenes", "platforms"]) {
      if (rec[arrField] !== undefined && !Array.isArray(rec[arrField])) {
        throw new Error(`[data] ${where} field "${arrField}" must be an array when present`);
      }
    }
    if (slugs.has(rec.slug as string)) {
      throw new Error(`[data] duplicate slug "${rec.slug}" at ${where}`);
    }
    slugs.add(rec.slug as string);
  });
  return raw as PromptCase[];
}

// import.meta.env.PROD is statically replaced by Vite, so the validate call is
// tree-shaken out of the production client bundle. It still runs during `dev`
// and during the SSG build (NODE_ENV !== production for the SSG render pass is
// not guaranteed, so we also gate on DEV/SSR) to fail fast on bad data.
const shouldValidate =
  !import.meta.env.PROD || import.meta.env.SSR || import.meta.env.DEV;

export const ALL_CASES: PromptCase[] = shouldValidate
  ? validateCases(casesJson)
  : (casesJson as PromptCase[]);
export const ALL_TEMPLATES: PromptTemplate[] = templatesJson as PromptTemplate[];

const BY_SLUG = new Map<string, PromptCase>(ALL_CASES.map((c) => [c.slug, c]));
const BY_ID = new Map<string, PromptCase>(ALL_CASES.map((c) => [c.id, c]));

export function getCaseBySlug(slug: string): PromptCase | undefined {
  return BY_SLUG.get(slug);
}
export function getCaseById(id: string): PromptCase | undefined {
  return BY_ID.get(id);
}

/** Cases grouped by user-intent bucket. Includes secondary buckets via `userCategories[]`. */
export function casesByUserCategory(key: string): PromptCase[] {
  return ALL_CASES.filter(
    (c) => c.userCategory === key || (c.userCategories ?? []).includes(key as never),
  );
}

/** "Related" picks: same userCategory first, then by overlapping tags. */
export function relatedCases(c: PromptCase, n = 6): PromptCase[] {
  const sameBucket = ALL_CASES.filter(
    (other) => other.id !== c.id && other.userCategory === c.userCategory,
  );
  if (sameBucket.length >= n) return sameBucket.slice(0, n);

  const tagSet = new Set([...c.tags, ...c.styles, ...c.scenes]);
  const byTag = ALL_CASES.filter(
    (other) =>
      other.id !== c.id &&
      other.userCategory !== c.userCategory &&
      [...other.tags, ...other.styles, ...other.scenes].some((t) => tagSet.has(t)),
  );
  return [...sameBucket, ...byTag].slice(0, n);
}

/** Sequential prev/next within a sorted-by-id list (for /case/:slug nav). */
export function caseNeighbors(c: PromptCase): {
  prev?: PromptCase;
  next?: PromptCase;
} {
  const i = ALL_CASES.findIndex((x) => x.id === c.id);
  if (i < 0) return {};
  return {
    prev: i + 1 < ALL_CASES.length ? ALL_CASES[i + 1] : undefined, // older
    next: i > 0 ? ALL_CASES[i - 1] : undefined, // newer
  };
}
