import type { PromptCase } from "../types";

/**
 * Homepage data — statically imported because it's tiny (~3KB gzip).
 * This file is generated by scripts/split-data.mjs and contains ONLY the
 * pre-selected cases the homepage needs (5 hero + 14 strip + 12 featured)
 * plus category tile stats. No prompts, no full dataset.
 *
 * Both SSG and client use the same import, so hydration is consistent.
 */
import homeData from "../../public/data/cases-home.json";

export interface HomeTile {
  slug: string;
  label: string;
  tagline: string;
  count: number;
  cover?: string;
}

export interface HomeData {
  hero: PromptCase[];
  strip: PromptCase[];
  featured: PromptCase[];
  tiles: HomeTile[];
  totalCount: number;
}

export const HOME_DATA: HomeData = homeData as HomeData;
