import { useEffect, useState } from "react";
import { fetchWithTimeout } from "../lib/fetchWithTimeout";

/**
 * Lightweight search index entry from cases-search.json.
 * Generated by scripts/split-data.mjs.
 */
export interface SearchEntry {
  id: string;
  t: string; // title
  c: string; // category
  uc: string; // userCategory
  s: string[]; // styles
  sc: string[]; // scenes
  p: string[]; // platforms
}

export interface FilterOptions {
  styles: string[];
  scenes: string[];
  platforms: string[];
}

let searchCache: SearchEntry[] | null = null;
let searchInflight: Promise<SearchEntry[]> | null = null;

let filterCache: FilterOptions | null = null;
let filterInflight: Promise<FilterOptions> | null = null;

/** Fetch the search index shard (cases-search.json, ~245KB gzip). */
export function loadSearchIndex(): Promise<SearchEntry[]> {
  if (searchCache) return Promise.resolve(searchCache);
  if (searchInflight) return searchInflight;

  const url = `${import.meta.env.BASE_URL}data/cases-search.json`;
  searchInflight = fetchWithTimeout(url, { cache: "force-cache", timeoutMs: 10000 })
    .then((r) => {
      if (!r.ok) throw new Error(`cases-search: ${r.status}`);
      return r.json();
    })
    .then((data: SearchEntry[]) => {
      searchCache = data;
      searchInflight = null;
      return data;
    })
    .catch((err) => {
      searchInflight = null;
      throw err;
    });

  return searchInflight;
}

/** Fetch the filter options shard (filter-options.json, <1KB). */
export function loadFilterOptions(): Promise<FilterOptions> {
  if (filterCache) return Promise.resolve(filterCache);
  if (filterInflight) return filterInflight;

  const url = `${import.meta.env.BASE_URL}data/filter-options.json`;
  filterInflight = fetchWithTimeout(url, { cache: "force-cache", timeoutMs: 10000 })
    .then((r) => {
      if (!r.ok) throw new Error(`filter-options: ${r.status}`);
      return r.json();
    })
    .then((data: FilterOptions) => {
      filterCache = data;
      filterInflight = null;
      return data;
    })
    .catch((err) => {
      filterInflight = null;
      throw err;
    });

  return filterInflight;
}

/** Synchronous access to cached search index. */
export function getCachedSearchIndex(): SearchEntry[] | null {
  return searchCache;
}

/** Synchronous access to cached filter options. */
export function getCachedFilterOptions(): FilterOptions | null {
  return filterCache;
}

/**
 * React hook that loads the search index + filter options on mount.
 * Returns null while loading. Subsequent navigations use cache.
 */
export function useSearchData(): {
  searchIndex: SearchEntry[] | null;
  filterOptions: FilterOptions | null;
} {
  const [searchIndex, setSearchIndex] = useState<SearchEntry[] | null>(searchCache);
  const [filterOptions, setFilterOptions] = useState<FilterOptions | null>(filterCache);

  useEffect(() => {
    if (!searchCache) {
      loadSearchIndex().then(setSearchIndex).catch(() => {});
    }
    if (!filterCache) {
      loadFilterOptions().then(setFilterOptions).catch(() => {});
    }
  }, []);

  return { searchIndex, filterOptions };
}
