import { memo, useEffect, useRef, useState } from "react";
import {
  localJpegSrcSet,
  localWebpSrcSet,
  pickLocalWebp,
  rawTransformUrl,
} from "../lib/img";

interface SmartImgProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Render widths used to build `srcset`. For local images these are
   *  filtered against the on-disk variant ladder in `lib/img.ts`. */
  widths?: number[];
  /** Width used for the fallback `src` attribute (smallest reasonable). */
  baseWidth?: number;
  sizes?: string;
  /** Optional media query that gates local <picture> sources. */
  media?: string;
  className?: string;
  style?: React.CSSProperties;
  objectFit?: React.CSSProperties["objectFit"];
  loading?: "eager" | "lazy";
  fetchPriority?: "high" | "low" | "auto";
  decoding?: "sync" | "async" | "auto";
  quality?: number;
  onLoad?: () => void;
  onError?: () => void;
  /** No-ops, kept for API compatibility with existing call sites. */
  lqip?: boolean;
  proxyTimeoutMs?: number;
}

const IMAGE_RETRY_DELAY_MS = 350;
const TRANSPARENT_PIXEL_SRC =
  "data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";

function appendRetryParam(url: string, retryToken: number): string {
  if (!url || retryToken === 0) return url;
  const hashIndex = url.indexOf("#");
  const base = hashIndex >= 0 ? url.slice(0, hashIndex) : url;
  const hash = hashIndex >= 0 ? url.slice(hashIndex) : "";
  const separator = base.includes("?") ? "&" : "?";
  return `${base}${separator}imgRetry=${retryToken}${hash}`;
}

function appendRetryParamToSrcSet(srcSet: string | undefined, retryToken: number) {
  if (!srcSet || retryToken === 0) return srcSet;
  return srcSet
    .split(",")
    .map((candidate) => {
      const trimmed = candidate.trim();
      const descriptorIndex = trimmed.search(/\s/);
      if (descriptorIndex < 0) return appendRetryParam(trimmed, retryToken);
      const url = trimmed.slice(0, descriptorIndex);
      const descriptor = trimmed.slice(descriptorIndex);
      return `${appendRetryParam(url, retryToken)}${descriptor}`;
    })
    .join(", ");
}

/**
 * Image with a calm loading state and responsive variant negotiation.
 *
 * For local /images/* paths (the production hot path), we render a
 * `<picture>` element with:
 *   - <source type="image/webp"> pointing at the on-disk WebP variants
 *     (320 / 480 / 640 / 960 px) generated by scripts/build-images.mjs
 *   - <img> fallback pointing at the canonical 1200 px JPEG, for the
 *     small percentage of clients without WebP support
 *
 * The browser picks the smallest variant whose `w` descriptor satisfies
 * the `sizes` constraint at the current DPR. On a phone (DPR 3, 50vw card,
 * ~360 CSS px wide) it grabs the 480 px WebP, ~30 KB. The previous
 * pipeline forced every <img> to download the 1200 px JPEG, ~170 KB.
 *
 * For external HTTP URLs the build pipeline missed (defensive edge case),
 * we route through wsrv as a one-off transform — single try, no ladder.
 *
 * Layout contract:
 *   The wrapper inherits className/style. Existing call sites pass
 *   `absolute inset-0 h-full w-full` to fill an aspect-ratio parent.
 *   The inner <img> always covers the wrapper via inline object-cover.
 */
function SmartImgImpl({
  src,
  alt,
  width,
  height,
  widths,
  baseWidth,
  sizes,
  media,
  className,
  style,
  objectFit = "cover",
  loading = "lazy",
  fetchPriority,
  decoding = "async",
  quality,
  onLoad,
  onError,
}: SmartImgProps) {
  const [loaded, setLoaded] = useState(false);
  const [errored, setErrored] = useState(false);
  const [retryToken, setRetryToken] = useState(0);
  // After wsrv proxy fails twice, try the original CDN URL directly as a
  // last-resort fallback. This catches cases where wsrv is down but the
  // origin CDN is reachable.
  const [directFallback, setDirectFallback] = useState(false);
  const imgRef = useRef<HTMLImageElement | null>(null);
  const signaledSrcRef = useRef<string | null>(null);
  const retryDelayRef = useRef<number | null>(null);

  // Decide the request URL. Local /images/* and /assets/* render as-is —
  // they're already optimised on disk. Upstream CDN images (YouMind) go
  // through wsrv for resize + WebP transcoding + better reachability in CN.
  const isLocalImg = /^\/images\//i.test(src);
  const isOtherSameOrigin =
    src.startsWith("/assets/") || src.startsWith("/uploads/");

  const baseW =
    baseWidth ??
    (widths && widths.length > 0 ? Math.min(...widths) : width);

  // ── Source resolution ──
  // For local /images/* we want the responsive <picture> path. For
  // /assets/ + /uploads/ we use the original src as-is (no variants on
  // disk for those). For external CDN URLs we proxy through wsrv with
  // responsive widths. When directFallback is active (wsrv failed twice),
  // we try the original CDN URL directly.
  const useDirect = directFallback && /^https?:\/\//i.test(src);
  const fallbackSrc = isLocalImg
    ? pickLocalWebp(src, baseW) // small WebP if the canonical .jpg has variants
    : isOtherSameOrigin || useDirect
      ? src
      : rawTransformUrl(src, { width: baseW, quality });

  // WebP srcset for local images. The <source> element will use this
  // when the browser supports image/webp (~96% in 2026 China).
  const webpSrcSet = isLocalImg ? localWebpSrcSet(src, widths) : "";

  // JPEG fallback srcset. For local images right now this is just the
  // canonical 1200 px JPEG; for external URLs we generate real wsrv-transformed
  // widths so the browser picks the right size.
  const jpegSrcSet = isLocalImg
    ? localJpegSrcSet(src)
    : isOtherSameOrigin || useDirect || !widths || widths.length === 0
      ? undefined
      : widths
          .map((w) => `${rawTransformUrl(src, { width: w, quality })} ${w}w`)
          .join(", ");

  const retrySrc = appendRetryParam(fallbackSrc, retryToken);
  const retryPictureFallbackSrc = appendRetryParam(src, retryToken);
  const retryWebpSrcSet = appendRetryParamToSrcSet(webpSrcSet, retryToken);
  const retryJpegSrcSet = appendRetryParamToSrcSet(jpegSrcSet, retryToken);

  const priorityAttr = fetchPriority
    ? ({ fetchpriority: fetchPriority } as { fetchpriority: NonNullable<SmartImgProps["fetchPriority"]> })
    : {};

  const clearRetryDelay = () => {
    if (retryDelayRef.current === null) return;
    window.clearTimeout(retryDelayRef.current);
    retryDelayRef.current = null;
  };

  const markLoaded = () => {
    clearRetryDelay();
    setLoaded(true);
    setErrored(false);
    if (signaledSrcRef.current !== retrySrc) {
      signaledSrcRef.current = retrySrc;
      onLoad?.();
    }
  };

  const markErrored = () => {
    if (retryToken === 0) {
      // First failure — retry the same (wsrv-proxied) URL after a short delay.
      clearRetryDelay();
      retryDelayRef.current = window.setTimeout(() => {
        retryDelayRef.current = null;
        setRetryToken((current) => (current === 0 ? 1 : current));
      }, IMAGE_RETRY_DELAY_MS);
      return;
    }

    // Second failure on the proxied URL. If the source is an external CDN
    // URL that we proxied through wsrv, try the ORIGINAL direct URL as a
    // last resort before giving up. This catches wsrv outages.
    if (!directFallback && /^https?:\/\//i.test(src) && !isOtherSameOrigin) {
      setDirectFallback(true);
      setLoaded(false);
      setErrored(false);
      return;
    }

    clearRetryDelay();
    setErrored(true);
    if (signaledSrcRef.current !== retrySrc) {
      signaledSrcRef.current = retrySrc;
      onError?.();
    }
  };

  useEffect(() => {
    signaledSrcRef.current = null;
    setLoaded(false);
    setErrored(false);
    setRetryToken(0);
    setDirectFallback(false);
    clearRetryDelay();

    return clearRetryDelay;
    // Reset only when the ORIGINAL source changes (not when directFallback
    // toggles, which would cause a reset loop).
  }, [src]);

  useEffect(() => {
    setLoaded(false);
    setErrored(false);

    const img = imgRef.current;
    if (!img) return;

    let cancelled = false;
    const syncFromElement = () => {
      if (cancelled || !img.complete) return;
      if (img.naturalWidth > 0) markLoaded();
      else markErrored();
    };

    img.addEventListener("load", markLoaded);
    img.addEventListener("error", markErrored);
    syncFromElement();
    const timers = [
      window.setTimeout(syncFromElement, 0),
      window.setTimeout(syncFromElement, 250),
      window.setTimeout(syncFromElement, 1000),
    ];

    return () => {
      cancelled = true;
      img.removeEventListener("load", markLoaded);
      img.removeEventListener("error", markErrored);
      timers.forEach((timer) => window.clearTimeout(timer));
    };
    // Run only when the resolved request URL changes. Parent callbacks often
    // close over local state, and re-running for callback identity would
    // re-signal a load that already happened.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [retrySrc]);

  // Common <img> props shared between the <picture> and bare-<img> paths.
  const imgProps = {
    ref: imgRef,
    src: retrySrc,
    sizes,
    alt,
    width,
    height,
    loading,
    decoding,
    ...priorityAttr,
    style: {
      display: "block" as const,
      width: "100%",
      height: "100%",
      objectFit,
      opacity: loaded ? 1 : 0,
      transition: "opacity 220ms ease-out",
    },
    onLoad: markLoaded,
    onError: markErrored,
  };
  const showSpinner =
    !loaded && !errored && (loading === "eager" || fetchPriority === "high");

  return (
    <div
      className={className}
      style={{
        ...style,
        overflow: "hidden",
        position: style?.position ?? "relative",
        // Calm dark skeleton. No animation — saves CPU on long mobile feeds.
        backgroundColor: loaded ? undefined : "var(--smart-img-skeleton, #1a1715)",
      }}
    >
      {showSpinner && <SpinnerOverlay />}
      {webpSrcSet ? (
        // Local image with WebP variants on disk: render <picture> so the
        // browser auto-picks WebP if it supports it, JPEG canonical otherwise.
        <picture className="smart-img-picture">
          <source media={media} type="image/webp" srcSet={retryWebpSrcSet} sizes={sizes} />
          {media && retryJpegSrcSet ? (
            <source media={media} srcSet={retryJpegSrcSet} sizes={sizes} />
          ) : null}
          <img
            {...imgProps}
            srcSet={media ? undefined : retryJpegSrcSet}
            // Override fallback src to the canonical JPEG when WebP is
            // unavailable — the smallest WebP isn't readable by clients
            // that hit the JPEG fallback, so they need the full file.
            src={media ? TRANSPARENT_PIXEL_SRC : retryPictureFallbackSrc}
          />
        </picture>
      ) : (
        // External URL or same-origin asset without variants: bare <img>.
        <img {...imgProps} srcSet={retryJpegSrcSet} />
      )}
    </div>
  );
}

/**
 * Centred ember spinner. Only shown for the true high-priority image path;
 * long mobile feeds use the static dark skeleton instead to avoid dozens of
 * simultaneous CSS animations.
 */
function SpinnerOverlay() {
  return (
    <div aria-hidden="true" className="smart-img-spinner">
      <span />
    </div>
  );
}

export const SmartImg = memo(SmartImgImpl);
