import { memo, useEffect, useRef, useState } from "react";
import {
  localJpegSrcSet,
  localWebpSrcSet,
  pickLocalWebp,
  rawTransformUrl,
} from "../lib/img";

interface SmartImgProps {
  src: string;
  alt: string;
  width: number;
  height: number;
  /** Render widths used to build `srcset`. For local images these are
   *  filtered against the on-disk variant ladder in `lib/img.ts`. */
  widths?: number[];
  /** Width used for the fallback `src` attribute (smallest reasonable). */
  baseWidth?: number;
  sizes?: string;
  className?: string;
  style?: React.CSSProperties;
  loading?: "eager" | "lazy";
  fetchPriority?: "high" | "low" | "auto";
  decoding?: "sync" | "async" | "auto";
  quality?: number;
  onLoad?: () => void;
  onError?: () => void;
  /** No-ops, kept for API compatibility with existing call sites. */
  lqip?: boolean;
  proxyTimeoutMs?: number;
}

/**
 * Image with a calm loading state and responsive variant negotiation.
 *
 * For local /images/* paths (the production hot path), we render a
 * `<picture>` element with:
 *   - <source type="image/webp"> pointing at the on-disk WebP variants
 *     (320 / 480 / 640 / 960 px) generated by scripts/build-images.mjs
 *   - <img> fallback pointing at the canonical 1200 px JPEG, for the
 *     small percentage of clients without WebP support
 *
 * The browser picks the smallest variant whose `w` descriptor satisfies
 * the `sizes` constraint at the current DPR. On a phone (DPR 3, 50vw card,
 * ~360 CSS px wide) it grabs the 480 px WebP, ~30 KB. The previous
 * pipeline forced every <img> to download the 1200 px JPEG, ~170 KB.
 *
 * For external HTTP URLs the build pipeline missed (defensive edge case),
 * we route through wsrv as a one-off transform — single try, no ladder.
 *
 * Layout contract:
 *   The wrapper inherits className/style. Existing call sites pass
 *   `absolute inset-0 h-full w-full` to fill an aspect-ratio parent.
 *   The inner <img> always covers the wrapper via inline object-cover.
 */
function SmartImgImpl({
  src,
  alt,
  width,
  height,
  widths,
  baseWidth,
  sizes,
  className,
  style,
  loading = "lazy",
  fetchPriority,
  decoding = "async",
  quality,
  onLoad,
  onError,
}: SmartImgProps) {
  const [loaded, setLoaded] = useState(false);
  const [errored, setErrored] = useState(false);
  const imgRef = useRef<HTMLImageElement | null>(null);
  const signaledSrcRef = useRef<string | null>(null);

  // Decide the request URL. Local /images/* and /assets/* render as-is —
  // they're already optimised on disk. Anything else (an http URL the
  // build pipeline didn't get to rewrite) goes through wsrv with a single
  // size-targeted request.
  const isLocalImg = /^\/images\//i.test(src);
  const isOtherSameOrigin =
    src.startsWith("/assets/") || src.startsWith("/uploads/");

  const baseW =
    baseWidth ??
    (widths && widths.length > 0 ? Math.min(...widths) : width);

  // ── Source resolution ──
  // For local /images/* we want the responsive <picture> path. For
  // /assets/ + /uploads/ we use the original src as-is (no variants on
  // disk for those). For external URLs we proxy through wsrv.
  const fallbackSrc = isLocalImg
    ? pickLocalWebp(src, baseW) // small WebP if the canonical .jpg has variants
    : isOtherSameOrigin
      ? src
      : rawTransformUrl(src, { width: baseW, quality });

  // WebP srcset for local images. The <source> element will use this
  // when the browser supports image/webp (~96% in 2026 China).
  const webpSrcSet = isLocalImg ? localWebpSrcSet(src, widths) : "";

  // JPEG fallback srcset. For local images right now this is just the
  // canonical 1200 px JPEG; for external defensive fallbacks we generate
  // real wsrv-transformed widths.
  const jpegSrcSet = isLocalImg
    ? localJpegSrcSet(src)
    : isOtherSameOrigin || !widths || widths.length === 0
      ? undefined
      : widths
          .map((w) => `${rawTransformUrl(src, { width: w, quality })} ${w}w`)
          .join(", ");

  const priorityAttr = fetchPriority
    ? ({ fetchpriority: fetchPriority } as { fetchpriority: NonNullable<SmartImgProps["fetchPriority"]> })
    : {};

  const markLoaded = () => {
    setLoaded(true);
    setErrored(false);
    if (signaledSrcRef.current !== fallbackSrc) {
      signaledSrcRef.current = fallbackSrc;
      onLoad?.();
    }
  };

  const markErrored = () => {
    setErrored(true);
    if (signaledSrcRef.current !== fallbackSrc) {
      signaledSrcRef.current = fallbackSrc;
      onError?.();
    }
  };

  useEffect(() => {
    signaledSrcRef.current = null;
    setLoaded(false);
    setErrored(false);

    const img = imgRef.current;
    if (!img) return;

    let cancelled = false;
    const syncFromElement = () => {
      if (cancelled || !img.complete) return;
      if (img.naturalWidth > 0) markLoaded();
      else markErrored();
    };

    img.addEventListener("load", markLoaded);
    img.addEventListener("error", markErrored);
    syncFromElement();
    const timers = [
      window.setTimeout(syncFromElement, 0),
      window.setTimeout(syncFromElement, 250),
      window.setTimeout(syncFromElement, 1000),
    ];

    return () => {
      cancelled = true;
      img.removeEventListener("load", markLoaded);
      img.removeEventListener("error", markErrored);
      timers.forEach((timer) => window.clearTimeout(timer));
    };
    // Run only when the resolved request URL changes. Parent callbacks often
    // close over local state, and re-running for callback identity would
    // re-signal a load that already happened.
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [fallbackSrc]);

  // Common <img> props shared between the <picture> and bare-<img> paths.
  const imgProps = {
    ref: imgRef,
    src: fallbackSrc,
    sizes,
    alt,
    width,
    height,
    loading,
    decoding,
    ...priorityAttr,
    style: {
      display: "block" as const,
      width: "100%",
      height: "100%",
      objectFit: "cover" as const,
      opacity: loaded ? 1 : 0,
      transition: "opacity 220ms ease-out",
    },
    onLoad: markLoaded,
    onError: markErrored,
  };

  return (
    <div
      className={className}
      style={{
        ...style,
        overflow: "hidden",
        position: style?.position ?? "relative",
        // Calm dark skeleton. No animation — saves CPU on long mobile feeds.
        backgroundColor: loaded ? undefined : "#1a1715",
      }}
    >
      {!loaded && !errored && <SpinnerOverlay />}
      {webpSrcSet ? (
        // Local image with WebP variants on disk: render <picture> so the
        // browser auto-picks WebP if it supports it, JPEG canonical otherwise.
        <picture>
          <source type="image/webp" srcSet={webpSrcSet} sizes={sizes} />
          <img
            {...imgProps}
            srcSet={jpegSrcSet}
            // Override fallback src to the canonical JPEG when WebP is
            // unavailable — the smallest WebP isn't readable by clients
            // that hit the JPEG fallback, so they need the full file.
            src={src}
          />
        </picture>
      ) : (
        // External URL or same-origin asset without variants: bare <img>.
        <img {...imgProps} srcSet={jpegSrcSet} />
      )}
    </div>
  );
}

/**
 * Centred ember spinner. Matches the homepage boot loader (.boot::after
 * in index.html) so the visual language is consistent from boot through
 * lazy-loaded card images.
 */
function SpinnerOverlay() {
  return (
    <div
      aria-hidden="true"
      style={{
        position: "absolute",
        inset: 0,
        display: "grid",
        placeItems: "center",
        pointerEvents: "none",
      }}
    >
      <div
        style={{
          width: 24,
          height: 24,
          borderRadius: "50%",
          border: "2px solid rgba(217,119,87,0.18)",
          borderTopColor: "#d97757",
          animation: "smartImgSpin 0.9s linear infinite",
        }}
      />
      <style>{`
        @keyframes smartImgSpin {
          to { transform: rotate(360deg); }
        }
      `}</style>
    </div>
  );
}

export const SmartImg = memo(SmartImgImpl);
