/**
 * Lightweight English→Chinese title translator for YouMind case titles.
 *
 * YouMind's GitHub data source only contains English titles. Their website
 * shows Chinese, but that translation isn't in the public data. This module
 * provides a rule-based translator that handles the structured, descriptive
 * title patterns YouMind uses (e.g. "Cinematic Golden Hour Female Portrait"
 * → "电影感黄金时刻女性肖像").
 *
 * It's NOT a general-purpose translator — it's tuned for the specific
 * vocabulary of AI image generation prompts (portrait, poster, anime, etc.).
 * Unknown words are kept as-is, which is acceptable since most titles are
 * composed of these common terms.
 *
 * Used by sync.mjs during normalizeCase to produce a Chinese title field.
 * The original English title is preserved in `titleEn` for reference.
 */

// ── Core vocabulary dictionary ────────────────────────────────────────
// Sorted by word length (longest first) so multi-word phrases match before
// single words (e.g. "golden hour" before "golden").
const PHRASES = [
  // Multi-word phrases
  ["golden hour", "黄金时刻"],
  ["character sheet", "角色设定图"],
  ["character design", "角色设计"],
  ["reference sheet", "参考图"],
  ["turnaround sheet", "三视图"],
  ["concept art", "概念设计"],
  ["double exposure", "双重曝光"],
  ["street style", "街头风"],
  ["street photography", "街头摄影"],
  ["film noir", "黑色电影"],
  ["color palette", "配色方案"],
  ["food photography", "美食摄影"],
  ["product photography", "产品摄影"],
  ["social media", "社交媒体"],
  ["youtube thumbnail", "视频缩略图"],
  ["watercolor", "水彩"],
  ["oil painting", "油画"],
  ["pencil sketch", "铅笔素描"],
  ["ink wash", "水墨"],
  ["paper craft", "纸艺"],
  ["paper cut", "剪纸"],
  ["isometric", "等距视角"],
  ["low poly", "低多边形"],
  ["pixel art", "像素画"],
  ["vapor wave", "蒸汽波"],
  ["vaporwave", "蒸汽波"],
  ["art nouveau", "新艺术运动"],
  ["art deco", "装饰艺术"],
  ["pop art", "波普艺术"],
  ["studio ghibli", "吉卜力风"],
  ["ghibli", "吉卜力风"],
  ["pixar", "皮克斯风"],
  ["disney", "迪士尼风"],
  ["claymation", "黏土动画"],
  ["clay", "黏土"],
  ["lego", "乐高"],
  ["minecraft", "我的世界"],
  ["blueprint", "蓝图"],
  ["exploded view", "爆炸图"],
  ["cutaway", "剖面图"],
  ["cross section", "截面图"],
  ["infographic", "信息图"],
  ["movie poster", "电影海报"],
  ["album cover", "专辑封面"],
  ["book cover", "书籍封面"],
  ["magazine cover", "杂志封面"],
  ["album art", "专辑美术"],
  ["line art", "线稿"],
  ["flat design", "扁平设计"],
  ["material design", "材料设计"],
  ["ui design", "UI 设计"],
  ["ux design", "UX 设计"],
  ["web design", "网页设计"],
  ["app icon", "应用图标"],
  ["loading screen", "加载页"],
  ["splash screen", "启动页"],
  ["user interface", "用户界面"],
  ["dashboard", "仪表盘"],
  ["landing page", "着陆页"],
  ["hero image", "主视觉"],
  ["key visual", "主视觉"],
  ["brand identity", "品牌识别"],
  ["brand logo", "品牌 Logo"],
  ["logo design", "Logo 设计"],
  ["packaging design", "包装设计"],
  ["product label", "产品标签"],
  ["menu design", "菜单设计"],
  ["birthday card", "生日贺卡"],
  ["greeting card", "贺卡"],
  ["playing card", "扑克牌"],
  ["tarot card", "塔罗牌"],
  ["trading card", "卡牌"],
  ["collectible", "收藏品"],
  ["figurine", "手办"],
  ["action figure", "可动人偶"],
  ["plush toy", "毛绒玩具"],
  ["stuffed animal", "毛绒动物"],
  ["mascot", "吉祥物"],
  ["avatar", "头像"],
  ["selfie", "自拍"],
  ["profile picture", "头像"],
  ["headshot", "头像照"],
  ["bust shot", "半身照"],
  ["full body", "全身"],
  ["upper body", "上半身"],
  ["close up", "特写"],
  ["wide shot", "远景"],
  ["establishing shot", " establishing shot"],
  ["bird's eye", "鸟瞰"],
  ["aerial view", "航拍"],
  ["top down", "俯视"],
  ["low angle", "低角度"],
  ["high angle", "高角度"],
  ["dutch angle", "倾斜角度"],
  ["over the shoulder", "过肩镜头"],
  ["point of view", "第一人称视角"],
  ["bokeh", "散景"],
  ["depth of field", "景深"],
  ["shallow depth", "浅景深"],
  ["long exposure", "长曝光"],
  ["motion blur", "动态模糊"],
  ["lens flare", "镜头光晕"],
  ["vignette", "暗角"],
  ["film grain", "胶片颗粒"],
  ["color grading", "调色"],
  ["color correction", "校色"],
  ["high key", "高调"],
  ["low key", "低调"],
  ["split lighting", "分割光"],
  ["rim lighting", "轮廓光"],
  ["backlit", "逆光"],
  ["silhouette", "剪影"],
  ["shadow play", "光影"],
  ["neon light", "霓虹灯"],
  ["neon", "霓虹"],
  ["glowing", "发光"],
  ["fluorescent", "荧光"],
  ["bioluminescent", "生物发光"],
  ["iridescent", "虹彩"],
  ["holographic", "全息"],
  ["metallic", "金属感"],
  ["chrome", "镀铬"],
  ["gold foil", "烫金"],
  ["foil stamping", "烫金"],
  ["embossed", "压花"],
  ["debossed", "凹印"],
  ["letterpress", "凸版印刷"],
  ["screen print", "丝网印刷"],
  ["risograph", "孔版印刷"],
  ["lino cut", " linocut"],
  ["woodcut", "木刻"],
  ["engraving", "版画"],
  ["etching", "蚀刻"],
  ["lithograph", "石版画"],
  ["uKIYO-e", "浮世绘"],
  ["sumi-e", "水墨画"],
  ["calligraphy", "书法"],
  ["brush stroke", "笔触"],
  ["watercolor", "水彩"],
  ["gouache", "水粉"],
  ["acrylic", "丙烯"],
  ["tempera", "蛋彩"],
  ["fresco", "湿壁画"],
  ["mural", "壁画"],
  ["graffiti", "涂鸦"],
  ["street art", "街头艺术"],
  ["sticker", "贴纸"],
  ["emoji", "表情"],
  ["stamp", "印章"],
  ["seal", "印章"],
  ["pattern", "图案"],
  ["texture", "纹理"],
  ["background", "背景"],
  ["wallpaper", "壁纸"],
  ["desktop", "桌面"],
  ["mobile", "手机"],
  ["smartphone", "智能手机"],
  ["tablet", "平板"],
  ["laptop", "笔记本"],
  ["monitor", "显示器"],
  ["screen", "屏幕"],
  ["interface", "界面"],
  ["wireframe", "线框图"],
  ["mockup", "样机"],
  ["prototype", "原型"],
  ["flowchart", "流程图"],
  ["diagram", "图表"],
  ["chart", "图表"],
  ["graph", "曲线图"],
  ["timeline", "时间线"],
  ["mind map", "思维导图"],
  ["comparison", "对比"],
  ["before after", "前后对比"],
  ["step by step", "步骤"],
  ["tutorial", "教程"],
  ["how to", "指南"],
  ["guide", "指南"],
  ["checklist", "清单"],
  ["summary", "摘要"],
  ["report", "报告"],
  ["presentation", "演示"],
  ["slide", "幻灯片"],
  ["pitch deck", "商业计划书"],
  ["portfolio", "作品集"],
  ["lookbook", "画册"],
  ["catalog", "目录"],
  ["brochure", "宣传册"],
  ["flyer", "传单"],
  ["leaflet", "折页"],
  ["coupon", "优惠券"],
  ["voucher", "代金券"],
  ["ticket", "门票"],
  ["invitation", "请柬"],
  ["certificate", "证书"],
  ["diploma", "文凭"],
  ["award", "奖项"],
  ["badge", "徽章"],
  ["medal", "奖牌"],
  ["trophy", "奖杯"],
  ["ribbon", "缎带"],
  ["banner", "横幅"],
  ["bunting", "彩旗"],
  ["garland", "花环"],
  ["wreath", "花圈"],
  ["bouquet", "花束"],
  ["flower", "花"],
  ["floral", "花卉"],
  ["botanical", "植物"],
  ["leaf", "叶子"],
  ["tree", "树"],
  ["forest", "森林"],
  ["woods", "树林"],
  ["jungle", "丛林"],
  ["mountain", "山"],
  ["hill", "丘陵"],
  ["valley", "山谷"],
  ["canyon", "峡谷"],
  ["cliff", "悬崖"],
  ["waterfall", "瀑布"],
  ["river", "河"],
  ["lake", "湖"],
  ["ocean", "海洋"],
  ["sea", "海"],
  ["beach", "海滩"],
  ["shore", "海岸"],
  ["island", "岛"],
  ["desert", "沙漠"],
  ["dune", "沙丘"],
  ["oasis", "绿洲"],
  ["meadow", "草地"],
  ["field", "田野"],
  ["prairie", "草原"],
  ["savanna", "稀树草原"],
  ["tundra", "苔原"],
  ["wetland", "湿地"],
  ["swamp", "沼泽"],
  ["marsh", "沼泽"],
  ["pond", "池塘"],
  ["stream", "溪流"],
  ["creek", "小溪"],
  ["spring", "泉水"],
  ["geyser", "间歇泉"],
  ["glacier", "冰川"],
  ["iceberg", "冰山"],
  ["snow", "雪"],
  ["ice", "冰"],
  ["frost", "霜"],
  ["fog", "雾"],
  ["mist", "薄雾"],
  ["cloud", "云"],
  ["sky", "天空"],
  ["sunrise", "日出"],
  ["sunset", "日落"],
  ["dawn", "黎明"],
  ["dusk", "黄昏"],
  ["twilight", "暮色"],
  ["midnight", "午夜"],
  ["noon", "正午"],
  ["morning", "早晨"],
  ["evening", "傍晚"],
  ["night", "夜晚"],
  ["day", "白天"],
  ["spring season", "春季"],
  ["summer", "夏天"],
  ["autumn", "秋天"],
  ["fall", "秋天"],
  ["winter", "冬天"],
  ["rainy", "雨天"],
  ["sunny", "晴天"],
  ["cloudy", "多云"],
  ["windy", "大风"],
  ["stormy", "暴风雨"],
  ["snowy", "下雪"],
  ["foggy", "有雾"],
  ["rainbow", "彩虹"],
  ["lightning", "闪电"],
  ["thunder", "雷"],
  ["weather", "天气"],
  ["season", "季节"],
  ["festive", "节日"],
  ["holiday", "假日"],
  ["christmas", "圣诞"],
  ["halloween", "万圣节"],
  ["new year", "新年"],
  ["lunar new year", "农历新年"],
  ["spring festival", "春节"],
  ["mid autumn", "中秋"],
  ["valentine", "情人节"],
  ["easter", "复活节"],
  ["thanksgiving", "感恩节"],
  ["birthday", "生日"],
  ["wedding", "婚礼"],
  ["anniversary", "纪念日"],
  ["graduation", "毕业"],
  ["ceremony", "仪式"],
  ["party", "派对"],
  ["celebration", "庆祝"],
  ["carnival", "狂欢节"],
  ["festival", "节日"],
  ["fair", "集市"],
  ["market", "市场"],
  ["bazaar", "集市"],
  ["shop", "商店"],
  ["store", "店铺"],
  ["boutique", "精品店"],
  ["cafe", "咖啡厅"],
  ["restaurant", "餐厅"],
  ["bar", "酒吧"],
  ["pub", "酒馆"],
  ["bakery", "面包店"],
  ["kitchen", "厨房"],
  ["dining", "用餐"],
  ["food", "美食"],
  ["meal", "餐"],
  ["dish", "菜品"],
  ["dessert", "甜点"],
  ["cake", "蛋糕"],
  ["pastry", "糕点"],
  ["bread", "面包"],
  ["coffee", "咖啡"],
  ["tea", "茶"],
  ["juice", "果汁"],
  ["smoothie", "冰沙"],
  ["cocktail", "鸡尾酒"],
  ["wine", "葡萄酒"],
  ["beer", "啤酒"],
  ["drink", "饮料"],
  ["beverage", "饮品"],
  ["fruit", "水果"],
  ["vegetable", "蔬菜"],
  ["meat", "肉"],
  ["seafood", "海鲜"],
  ["noodle", "面"],
  ["rice", "米饭"],
  ["soup", "汤"],
  ["salad", "沙拉"],
  ["sandwich", "三明治"],
  ["burger", "汉堡"],
  ["pizza", "披萨"],
  ["sushi", "寿司"],
  ["ramen", "拉面"],
  ["dumpling", "饺子"],
  ["dim sum", "点心"],
  ["bbq", "烧烤"],
  ["grill", "烤"],
  ["fries", "薯条"],
  ["snack", "零食"],
  ["candy", "糖果"],
  ["chocolate", "巧克力"],
  ["ice cream", "冰淇淋"],
  ["donut", "甜甜圈"],
  ["cookie", "曲奇"],
  ["pie", "派"],
  ["pancake", "煎饼"],
  ["waffle", "华夫饼"],
];

// Single-word dictionary (applied after phrases)
const WORDS = {
  // Subjects
  portrait: "肖像",
  poster: "海报",
  fashion: "时尚",
  japanese: "日系",
  anime: "动漫",
  manga: "漫画",
  comic: "漫画",
  cartoon: "卡通",
  cinematic: "电影感",
  editorial: "杂志风",
  luxury: "奢华",
  premium: "高级",
  minimalist: "极简",
  minimalism: "极简",
  realistic: "写实",
  photorealistic: "照片级写实",
  surreal: "超现实",
  surrealism: "超现实",
  fantasy: "奇幻",
  scifi: "科幻",
  "sci-fi": "科幻",
  cyberpunk: "赛博朋克",
  steampunk: "蒸汽朋克",
  retro: "复古",
  vintage: "复古",
  classic: "经典",
  classical: "古典",
  modern: "现代",
  contemporary: "当代",
  futuristic: "未来感",
  urban: "都市",
  rural: "乡村",
  industrial: "工业风",
  rustic: "乡村风",
  bohemian: "波西米亚",
  boho: "波西米亚",
  gothic: "哥特",
  baroque: "巴洛克",
  rococo: "洛可可",
  renaissance: "文艺复兴",
  impressionist: "印象派",
  impressionism: "印象派",
  expressionist: "表现主义",
  cubist: "立体派",
  cubism: "立体主义",
  surrealist: "超现实主义",
  pop: "波普",
  kawaii: "可爱",
  chibi: "Q版",
  moe: "萌系",
  lolita: "洛丽塔",
  gothic: "哥特",
  punk: "朋克",
  grunge: "颓废",
  hipster: "文艺青年",
  preppy: "学院风",
  business: "商务",
  casual: "休闲",
  formal: "正式",
  elegant: "优雅",
  gorgeous: "华丽",
  beautiful: "美丽",
  cute: "可爱",
  pretty: "漂亮",
  handsome: "英俊",
  stunning: "惊艳",
  breathtaking: "震撼",
  magnificent: "壮丽",
  majestic: "宏伟",
  epic: "史诗",
  dramatic: "戏剧性",
  dynamic: "动态",
  energetic: "活力",
  vibrant: "鲜艳",
  vivid: "生动",
  colorful: "多彩",
  monochrome: "单色",
 黑白: "黑白",
  grayscale: "灰度",
  sepia: "棕褐色",
  duotone: "双色调",
  pastel: "柔和色",
  neon: "霓虹",
  bright: "明亮",
  dark: "暗调",
  moody: "情绪化",
  gloomy: "阴郁",
  cheerful: "欢快",
  joyful: "快乐",
  happy: "开心",
  sad: "悲伤",
  melancholic: "忧郁",
  serene: "宁静",
  peaceful: "平和",
  calm: "平静",
  tranquil: "安宁",
  cozy: "温馨",
  warm: "温暖",
  cool: "清凉",
  cold: "寒冷",
  hot: "炎热",
  fresh: "清新",
  clean: "干净",
  pure: "纯净",
  soft: "柔和",
  hard: "硬朗",
  sharp: "锐利",
  blurry: "模糊",
  smooth: "平滑",
  rough: "粗糙",
  glossy: "光泽",
  matte: "哑光",
  shiny: "闪亮",
  sparkling: "闪耀",
  glittering: "闪烁",
  twinkling: "闪烁",
  glowing: "发光",
  // People
  woman: "女性",
  women: "女性",
  man: "男性",
  men: "男性",
  girl: "女孩",
  boy: "男孩",
  child: "儿童",
  kid: "孩子",
  baby: "婴儿",
  teen: "青少年",
  adult: "成人",
  elderly: "老人",
  couple: "情侣",
  family: "家庭",
  group: "群体",
  crowd: "人群",
  people: "人物",
  person: "人物",
  human: "人类",
  face: "面部",
  head: "头部",
  hair: "头发",
  eye: "眼睛",
  smile: "微笑",
  expression: "表情",
  pose: "姿势",
  gesture: "手势",
  // Clothing
  dress: "连衣裙",
  outfit: "穿搭",
  costume: "服装",
  uniform: "制服",
  suit: "西装",
  jacket: "外套",
  coat: "大衣",
  shirt: "衬衫",
  skirt: "裙子",
  pants: "裤子",
  jeans: "牛仔裤",
  shoes: "鞋子",
  boots: "靴子",
  hat: "帽子",
  cap: "帽子",
  glasses: "眼镜",
  jewelry: "首饰",
  necklace: "项链",
  ring: "戒指",
  earrings: "耳环",
  watch: "手表",
  bag: "包",
  purse: "手提包",
  backpack: "背包",
  umbrella: "雨伞",
  fan: "扇子",
  sword: "剑",
  weapon: "武器",
  shield: "盾牌",
  armor: "盔甲",
  helmet: "头盔",
  crown: "皇冠",
  tiara: "头饰",
  veil: "面纱",
  mask: "面具",
  cape: "披风",
  cloak: "斗篷",
  robe: "长袍",
  gown: "礼服",
  kimono: "和服",
  hanbok: "韩服",
  cheongsam: "旗袍",
  qipao: "旗袍",
  hanfu: "汉服",
  sari: "纱丽",
  sarong: "纱笼",
  // Colors
  red: "红色",
  blue: "蓝色",
  green: "绿色",
  yellow: "黄色",
  orange: "橙色",
  purple: "紫色",
  pink: "粉色",
  brown: "棕色",
  black: "黑色",
  white: "白色",
  gray: "灰色",
  grey: "灰色",
  silver: "银色",
  gold: "金色",
  bronze: "铜色",
  copper: "铜色",
  cream: "奶油色",
  ivory: "象牙白",
  beige: "米色",
  tan: "棕褐色",
  peach: "桃色",
  lavender: "薰衣草色",
  mint: "薄荷色",
  sage: "鼠尾草色",
  olive: "橄榄色",
  navy: "藏青",
  teal: "蓝绿色",
  turquoise: "绿松石色",
  cyan: "青色",
  magenta: "洋红",
  crimson: "深红",
  maroon: "栗色",
  burgundy: "勃艮第",
  coral: "珊瑚色",
  salmon: "鲑鱼色",
  rose: "玫瑰色",
  ruby: "宝石红",
  emerald: "翡翠绿",
  sapphire: "宝石蓝",
  amethyst: "紫水晶",
  diamond: "钻石",
  pearl: "珍珠",
  opal: "蛋白石",
  // Style/technique
  style: "风格",
  art: "艺术",
  design: "设计",
  photo: "照片",
  photograph: "照片",
  photography: "摄影",
  render: "渲染",
  "3d": "3D",
  "2d": "2D",
  illustration: "插画",
  drawing: "绘画",
  painting: "画作",
  sketch: "素描",
  render: "渲染",
  model: "模型",
  sculpture: "雕塑",
  statue: "雕像",
  figurine: "手办",
  toy: "玩具",
  game: "游戏",
  video: "视频",
  film: "电影",
  movie: "电影",
  animation: "动画",
  animated: "动画",
  cartoon: "卡通",
  character: "角色",
  hero: "主角",
  villain: "反派",
  creature: "生物",
  monster: "怪物",
  animal: "动物",
  pet: "宠物",
  cat: "猫",
  dog: "狗",
  bird: "鸟",
  fish: "鱼",
  horse: "马",
  rabbit: "兔子",
  bunny: "兔子",
  bear: "熊",
  panda: "熊猫",
  fox: "狐狸",
  wolf: "狼",
  lion: "狮子",
  tiger: "老虎",
  dragon: "龙",
  phoenix: "凤凰",
  unicorn: "独角兽",
  fairy: "仙女",
  angel: "天使",
  demon: "恶魔",
  ghost: "幽灵",
  zombie: "丧尸",
  vampire: "吸血鬼",
  werewolf: "狼人",
  robot: "机器人",
  cyborg: "半机械人",
  mech: "机甲",
  spaceship: "飞船",
  rocket: "火箭",
  car: "汽车",
  vehicle: "车辆",
  truck: "卡车",
  motorcycle: "摩托车",
  bicycle: "自行车",
  train: "火车",
  airplane: "飞机",
  boat: "船",
  ship: "船",
  architecture: "建筑",
  building: "建筑",
  house: "房屋",
  tower: "塔",
  castle: "城堡",
  palace: "宫殿",
  temple: "寺庙",
  church: "教堂",
  bridge: "桥",
  road: "道路",
  street: "街道",
  city: "城市",
  town: "小镇",
  village: "村庄",
  interior: "室内",
  exterior: "外部",
  room: "房间",
  bedroom: "卧室",
  living: "客厅",
  kitchen: "厨房",
  bathroom: "浴室",
  office: "办公室",
  studio: "工作室",
  // Additional common title words
  travel: "旅行",
  landscape: "风景",
  nature: "自然",
  aesthetic: "美学",
  inspired: "灵感",
  female: "女性",
  male: "男性",
  shadows: "光影",
  shadow: "影子",
  light: "光线",
  lighting: "灯光",
  leaves: "树叶",
  leaf: "叶子",
  summer: "夏天",
  spring: "春天",
  winter: "冬天",
  autumn: "秋天",
  flower: "花",
  flowers: "花",
  garden: "花园",
  park: "公园",
  space: "空间",
  abstract: "抽象",
  typographic: "排版",
  typography: "字体",
  lettering: "字体",
  calligraphy: "书法",
  geometric: "几何",
  organic: "有机",
  hand: "手绘",
  handdrawn: "手绘",
  sketch: "手绘",
  doodle: "涂鸦",
  collage: "拼贴",
  mixed: "混合",
  media: "媒介",
  digital: "数字",
  traditional: "传统",
  oriental: "东方",
  asian: "亚洲",
  european: "欧洲",
  western: "西方",
  chinese: "中国",
  korean: "韩国",
  american: "美国",
  victorian: "维多利亚",
  medieval: "中世纪",
  ancient: "古代",
  mythology: "神话",
  magical: "魔法",
  enchanted: "魔法",
  mystical: "神秘",
  ethereal: "空灵",
  dreamy: "梦幻",
  dream: "梦",
  celestial: "天界",
  cosmic: "宇宙",
  galaxy: "星系",
  star: "星星",
  stars: "星空",
  moon: "月亮",
  planet: "星球",
  // Additional common title words (added after testing)
  sheet: "表",
  scene: "场景",
  environment: "环境",
  shot: "照",
  night: "夜晚",
  city: "城市",
  lights: "灯光",
  light: "光",
  reflection: "倒影",
  reflective: "反光",
  white: "白色",
  black: "黑色",
  background: "背景",
  model: "模特",
  set: "套装",
  collection: "合集",
  series: "系列",
  pack: "包",
  bundle: "合集",
  kit: "套件",
  board: "展板",
  page: "页面",
  spread: "跨页",
  layout: "排版",
  grid: "网格",
  frame: "相框",
  border: "边框",
  edge: "边缘",
  corner: "角落",
  center: "中心",
  middle: "中间",
  top: "顶部",
  bottom: "底部",
  side: "侧面",
  front: "正面",
  back: "背面",
  left: "左",
  right: "右",
  full: "完整",
  half: "半",
  detail: "细节",
  closeup: "特写",
  macro: "微距",
  wide: "广角",
  panorama: "全景",
  panoramic: "全景",
  "360": "360度",
  degree: "度",
  angle: "角度",
  view: "视角",
  perspective: "透视",
  isometric: "等距",
  orthographic: "正交",
  perspective: "透视",
  front: "正面",
  profile: "侧面",
  threequarter: "四分之三",
  landscape: "横版",
  square: "正方形",
  circle: "圆形",
  triangle: "三角形",
  rectangle: "矩形",
  diamond: "菱形",
  hexagon: "六边形",
  octagon: "八边形",
  star: "星形",
  heart: "心形",
  spiral: "螺旋",
  wave: "波浪",
  curve: "曲线",
  line: "线条",
  dot: "点",
  pattern: "图案",
  grid: "网格",
  texture: "纹理",
  gradient: "渐变",
  blend: "混合",
  overlay: "叠加",
  layer: "图层",
  mask: "遮罩",
  filter: "滤镜",
  effect: "效果",
  glow: "辉光",
  blur: "模糊",
  sharpen: "锐化",
  noise: "噪点",
  grain: "颗粒",
  scan: "扫描",
  print: "印刷",
  digital: "数字",
  analog: "模拟",
  film: "胶片",
  polaroid: "拍立得",
  instax: "instax",
  vintage: "复古",
  retro: "怀旧",
  nostalgia: "怀旧",
  memory: "记忆",
  dream: "梦幻",
  fantasy: "奇幻",
  wonderland: "仙境",
  fairytale: "童话",
  storybook: "故事书",
  narrative: "叙事",
  storytelling: "叙事",
  epic: "史诗",
  legendary: "传奇",
  mythical: "神话",
  divine: "神圣",
  sacred: "神圣",
  holy: "神圣",
  blessing: "祝福",
  prayer: "祈祷",
  meditation: "冥想",
  zen: "禅",
  peaceful: "宁静",
  serene: "安详",
  tranquil: "恬静",
  harmony: "和谐",
  balance: "平衡",
  symmetry: "对称",
  asymmetry: "不对称",
  chaos: "混沌",
  order: "秩序",
  structure: "结构",
  form: "形态",
  shape: "形状",
  volume: "体积",
  mass: "体量",
  weight: "重量",
  scale: "比例",
  proportion: "比例",
  ratio: "比率",
  size: "尺寸",
  large: "大",
  small: "小",
  giant: "巨大",
  tiny: "微小",
  massive: "庞大",
  monumental: "纪念碑式",
  miniature: "微缩",
  diorama: "微缩模型",
  tilt: "移轴",
  shift: "移位",
  bokeh: "散景",
  // High-frequency title words from YouMind data analysis
  prompt: "提示词",
  transformation: "变身",
  panel: "分镜",
  screenshot: "截图",
  cover: "封面",
  advertisement: "广告",
  illustration: "插画",
  image: "图像",
  streetwear: "街头潮服",
  mockup: "样机",
  candid: "抓拍",
  campaign: "活动",
  world: "世界",
  magazine: "杂志",
  censored: "审查版",
  generator: "生成器",
  concept: "概念",
  football: "足球",
  sports: "运动",
  high: "高",
  lifestyle: "生活方式",
  underground: "地下",
  subway: "地铁",
  escape: "逃脱",
  route: "路线",
  chase: "追逐",
  rider: "骑手",
  meadow: "草地",
  flight: "飞行",
  encounter: "遭遇",
  heroic: "英雄",
  england: "英国",
  footballer: "球员",
  love: "爱",
  gas: "加油站",
  station: "站",
  sunrise: "日出",
  cosplay: "cosplay",
  tavern: "酒馆",
  gathering: "聚会",
  hamster: "仓鼠",
  summons: "召唤",
  sol: "太阳",
  surrounded: "环绕",
  cats: "猫",
  cow: "牛仔",
  watering: "浇水",
  sunflowers: "向日葵",
  voxel: "体素",
  website: "网站",
  building: "建筑",
  rainy: "雨天",
  hoodie: "连帽衫",
  goth: "哥特",
  veranda: "阳台",
  cream: "奶油色",
  megaphone: "扩音器",
  suit: "西装",
  outfit: "穿搭",
  paint: "彩绘",
  facial: "面部",
  bird: "鸟",
  beast: "兽",
  monochrome: "单色",
  surreal: "超现实",
  white: "白色",
  haired: "发色",
  griffin: "狮鹫",
  inspired: "风格",
  aesthetic: "美学",
  // Common connectors (kept as-is or translated)
  with: "带",
  and: "与",
  of: "",
  in: "",
  on: "",
  at: "",
  the: "",
  a: "",
  an: "",
  for: "",
  under: "",
  over: "",
  near: "",
  by: "",
  from: "",
  to: "",
  into: "",
  under: "",
};

/**
 * Translate a YouMind English title to Chinese using phrase + word dictionary.
 * Falls back to keeping unknown words as-is.
 *
 * Uses word-boundary regex matching so partial words aren't corrupted
 * (e.g. "street" doesn't get `tree→树` injected inside it).
 *
 * @param {string} title - English title (e.g. "Cinematic Golden Hour Female Portrait")
 * @returns {string} Chinese title (e.g. "电影感黄金时刻女性肖像")
 */
export function translateTitle(title) {
  if (!title || typeof title !== "string") return title;

  let result = title;

  // Step 1: Replace multi-word phrases with word boundaries (longest first).
  // Sort by length descending so "golden hour" matches before "golden".
  const sortedPhrases = [...PHRASES].sort((a, b) => b[0].length - a[0].length);
  for (const [en, zh] of sortedPhrases) {
    if (!en || !zh) continue;
    // Use word boundaries on both sides. \b doesn't work well with
    // non-ASCII, but our phrases are all ASCII English.
    const regex = new RegExp("\\b" + escapeRegex(en) + "\\b", "gi");
    result = result.replace(regex, zh);
  }

  // Step 2: Replace single words with word boundaries (longest first).
  // Sort WORDS keys by length descending to avoid partial matches.
  const sortedWords = Object.entries(WORDS).sort((a, b) => b[0].length - a[0].length);
  for (const [en, zh] of sortedWords) {
    if (!en) continue;
    const regex = new RegExp("\\b" + escapeRegex(en) + "\\b", "gi");
    result = result.replace(regex, zh);
  }

  // Step 3: Clean up — collapse multiple spaces, remove empty connectors.
  result = result
    .replace(/\s+/g, " ")
    .replace(/\s+[与带]\s+/g, " ")
    .replace(/^\s*[与带]\s+/g, "")
    .replace(/\s*[与带]\s*$/g, "")
    .trim();

  // If the result is mostly still English (low translation rate), keep original.
  const chineseChars = (result.match(/[\u4e00-\u9fff]/g) || []).length;
  const totalChars = result.replace(/\s/g, "").length;
  if (totalChars > 0 && chineseChars / totalChars < 0.15) {
    return title;
  }

  return result || title;
}

function escapeRegex(str) {
  return str.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}
