/**
 * Public data shape served from `/data/cases.json`.
 *
 * The file is generated by:
 *   1. `scripts/sync.mjs` — pulls the latest upstream awesome-gpt-image-2 dataset.
 *   2. `scripts/migrate-v2.mjs` — enriches each case with SEO + structural fields.
 *
 * v2 fields are required by the new detail page / SEO pipeline. Older optional
 * fields (`promptPreview`, `imageAlt`, `source`, `githubUrl`) remain optional
 * to keep the legacy admin/runtime tolerant.
 */

/** User-intent category bucket. UI labels live in `src/lib/userCategories.ts`. */
export type UserCategoryKey =
  | "xhs-cover"
  | "wechat-grid"
  | "merchant-poster"
  | "portrait"
  | "kids-portrait"
  | "3d-ip"
  | "ecommerce"
  | "travel-poster"
  | "brand-kv"
  | "festival"
  | "infographic"
  | "sticker"
  | "ui-screenshot"
  | "poster-general"
  | "illustration"
  | "classical"
  | "storyboard"
  | "architecture"
  | "other";

export type Platform = "xiaohongshu" | "wechat" | "douyin" | "ec" | "offline";

export type CommercialFlag = "personal" | "commercial" | "ask";

export type Ratio = "1:1" | "4:5" | "3:4" | "9:16" | "16:9" | "2:3" | string;

export interface PromptCase {
  // ─── identity ───
  id: string;
  /** SEO-friendly URL piece, e.g. `ren-wu-fa-xing-she-ji-100004`. */
  slug: string;
  title: string;
  category: string;

  // ─── classification ───
  tags: string[];
  styles: string[];
  scenes: string[];
  /** v2 user-intent bucket — drives `/category/:slug` pages and homepage tiles. */
  userCategory: UserCategoryKey;
  /** v2 distribution channels this case is well-suited for. */
  platforms: Platform[];

  // ─── image ───
  imageUrl: string;
  imageAlt?: string;
  /** v2 aspect ratio used for un-cropped layout (e.g. `9:16`). */
  ratio: Ratio;

  // ─── prompt ───
  /**
   * Short preview shown on cards. Full prompt lazy-loads from
   * `data/prompts/{id}.json` via the `usePrompt` hook.
   */
  promptPreview?: string;

  // ─── metadata ───
  source?: string;
  githubUrl?: string;
  /** v2 1–5, derived from prompt complexity. */
  difficulty: 1 | 2 | 3 | 4 | 5;
  /** v2 commercial usage flag. */
  commercialOk: CommercialFlag;
  /** v2 ISO timestamp. */
  createdAt: string;

  // ─── SEO ───
  seoTitle: string;
  seoDescription: string;
}

export interface PromptTemplate {
  id: string;
  title: string;
  category: string;
  tags: string[];
  description: string;
  cover: string;
  prompt: string;
  useWhen: string;
}
